// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWRZaLgoKEeIOZa9uuuBwIvQ4hggB9joE',
    appId: '1:558827712643:web:08df9e1b0836b4357febb6',
    messagingSenderId: '558827712643',
    projectId: 'shabus-1f7a8',
    authDomain: 'shabus-1f7a8.firebaseapp.com',
    storageBucket: 'shabus-1f7a8.firebasestorage.app',
    measurementId: 'G-E5T2ST7NWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7oDJkZRVJ_Sb2ynQKSKgpQljhIWnnvYc',
    appId: '1:558827712643:android:778e19e36311dd977febb6',
    messagingSenderId: '558827712643',
    projectId: 'shabus-1f7a8',
    storageBucket: 'shabus-1f7a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANeDd8ahpLEE-8nCh5exHahuMs25KZ1zA',
    appId: '1:558827712643:ios:833a0ff7faade0477febb6',
    messagingSenderId: '558827712643',
    projectId: 'shabus-1f7a8',
    storageBucket: 'shabus-1f7a8.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANeDd8ahpLEE-8nCh5exHahuMs25KZ1zA',
    appId: '1:558827712643:ios:833a0ff7faade0477febb6',
    messagingSenderId: '558827712643',
    projectId: 'shabus-1f7a8',
    storageBucket: 'shabus-1f7a8.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWRZaLgoKEeIOZa9uuuBwIvQ4hggB9joE',
    appId: '1:558827712643:web:0d74b385397f60537febb6',
    messagingSenderId: '558827712643',
    projectId: 'shabus-1f7a8',
    authDomain: 'shabus-1f7a8.firebaseapp.com',
    storageBucket: 'shabus-1f7a8.firebasestorage.app',
    measurementId: 'G-6CBYGD7JV2',
  );

}